### ISSUE TITLE
Option to offset the icons halfway within the token square

### ISSUE THREAD

**Issue by apoapostolov** [jessev14/status-icon-tweaks#1]
Option to set margin offset (in pixels) that would allow the icons to partially enter the square of the token. The current design makes it hard if there's another token north of the current one, this would make the status icons of the bottom token to fully overlap the top token. By offsetting the icons partially over the below token it would make them more clear that they apply to it.

**Comment by jessev14** [comment]
good idea. what I'll do is add a slider for offset distance.

**Comment by jessev14** [comment]
Give version 1.1.0 a try.
