### ISSUE TITLE
Problem with Status Icon Tweaks on V10

### ISSUE THREAD

**Issue by arkangel85** [jessev14/status-icon-tweaks#7]
when the module will be activated the maps will not be loaded and we got this error:

![image](https://user-images.githubusercontent.com/93746418/188339006-e95d2744-012f-424e-834f-86a31958b93c.png)

**Comment by Fmerrick** [comment]
I had the same issue. I really like this module, I hope it gets updated to support V10 eventually.

**Comment by steveculshaw** [comment]
Ah ha ... I've just installed this module on my previously working v10 instance and getting this **"Canvas drawing failed"** error.

Disabled the module, and everything is back working.

**Comment by arkangel85** [comment]
I suppose this project is abandoned

**Comment by jessev14** [comment]
This project is not abandoned.

I prioritize my paid commissions over the free modules I create in my spare time.

Feel free to donate to support the development efforts for these projects.

**Comment by steveculshaw** [comment]
Totally understandable, everyone's got to eat!

Thanks for the response

Looking forward to a v10 compatible version
