### ISSUE TITLE
Libwrapper dependency name incorrect in module.json in v1.0.0

### ISSUE THREAD

**Issue by WildBillLives** [jessev14/status-icon-tweaks#8]
In the latest version of status-icon-tweaks the name for the libwrapper dependency is incorrect, and thus the module cannot be loaded due to 'issues in dependencies'.

The current module.json shows the libwrapper name as : 

_"id": "libwrapper"_

but it **should** be:

_"id": "lib-wrapper"_

**Comment by jessev14** [comment]
Appreciate the heads up. Fixed in v2.0.2.
